# Additional Spring Boot application properties
server:
  port: 8080

rabbitmq:
  exchange_name: exchange_demo
  queue: queue_demo
  routing_key: routing_key_demo
  json_queue: json_queue
  json_routing_key: json_routing_key
  dlExchange: dlx
  dl_Queue: dlq
  dl_routing_key: dlk


#spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    virtual-host: /
#    connection-timeout: 60000
#    requested-heartbeat: 60
#    ssl:
#      enabled: false